[workspace]
members = [
  "services/filemonitor",
  "services/phd2-guider",
  "services/ppba-driver",
  "services/qhy-focuser",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Igor von Nyssen <igor@vonnyssen.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ivonnyssen/rusty_photon"
description = "Rusty Photon - An astrophotography application"

[workspace.dependencies]
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
clap = { version = "4.5.55", features = ["derive"] }
regex = "1.12.2"
async-trait = "0.1.89"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tokio-test = "0.4.5"
proptest = "1.9.0"
fitsio = "0.21.9"
thiserror = "2.0.18"
base64 = "0.22.1"
mockall = "0.14.0"
tokio-serial = "5.4"
ascom-alpaca = { git = "https://github.com/ivonnyssen/ascom-alpaca-rs.git", branch = "feature/conformu-settings-file", default-features = false }
reqwest = "0.12"
